# docker/Dockerfile.mlflow
FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir mlflow boto3 psycopg2-binary

# Ports & envs
EXPOSE 5000
ENV MLFLOW_BACKEND_URI="" \
    MLFLOW_ARTIFACT_ROOT=""

# You’ll set MLFLOW_BACKEND_URI (RDS/Postgres) and MLFLOW_ARTIFACT_ROOT (S3 path)
CMD ["sh", "-c", "mlflow server \
    --backend-store-uri ${MLFLOW_BACKEND_URI} \
    --default-artifact-root ${MLFLOW_ARTIFACT_ROOT} \
    --host 0.0.0.0 --port 5000"]
