artifact_location: file:C:\Users\Jcast\OneDrive\Documents\sports-repo\alpha_signal_engine\mlruns_local/0
creation_time: 1765245633204
experiment_id: '0'
last_update_time: 1765245633204
lifecycle_stage: active
name: Default
