artifact_location: file:C:\Users\Jcast\OneDrive\Documents\sports-repo\alpha_signal_engine\mlruns_local/476159873114401147
creation_time: 1765245633228
experiment_id: '476159873114401147'
last_update_time: 1765245633228
lifecycle_stage: active
name: sharpsignal-sagemaker
